extends: hf_default.yaml
model:
  name: google/gemma-4-E4B-it
  tokenizer: google/gemma-4-E4B-it
  processor: google/gemma-4-E4B-it
  model_class: image_text_to_text
  attn_implementation: sdpa
  batch_size: 1
  max_seq_length: 4096
  message_format: multimodal
  padding_side: left

generation:
  max_new_tokens: 1800
  temperature: 0.7
  do_sample: true
  top_p: 0.95
  cache_implementation: static
