extends: hf_default.yaml
model:
  name: google/gemma-3-27b-it
  tokenizer: google/gemma-3-27b-it
  processor: google/gemma-3-27b-it
  dtype: bfloat16
  model_class: image_text_to_text
  batch_size: 1
  max_seq_length: 8192
  message_format: multimodal

generation:
  max_new_tokens: 2048
  temperature: 0.7
  do_sample: true
  top_p: 0.95
