#!/usr/bin/env python3
"""Render the v3 circulation audit from the canonical JSON records."""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "configs" / "primary_motif_manifest_v3.json"
DEFAULT_NARRATIVES = ROOT / "configs" / "motif_narratives_v3.json"
DEFAULT_QUALITY = ROOT / "configs" / "motif_quality_review_v3.json"
DEFAULT_RECOMMENDATION = ROOT / "configs" / "motif_selection_recommendation_v3.json"
DEFAULT_OUTPUT = ROOT / "docs" / "motif_circulation_audit_v3.md"


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _tier_map(recommendation: dict) -> dict[str, str]:
    tiers = (
        ("main", "recommended_primary_ids"),
        ("viable alternate", "viable_alternate_ids"),
        ("auxiliary variant", "auxiliary_variant_ids"),
        ("high-sensitivity optional", "high_sensitivity_optional_ids"),
    )
    result: dict[str, str] = {}
    for label, key in tiers:
        for motif_id in recommendation.get(key, []):
            result[motif_id] = label
    return result


def render_document(
    manifest: dict,
    narratives: dict,
    quality: dict,
    recommendation: dict,
) -> str:
    candidate_items = [
        *manifest.get("motifs", []),
        *manifest.get("additional_eligible_candidates", []),
    ]
    narrative_by_id = {
        record["motif_id"]: record for record in narratives.get("records", [])
    }
    quality_by_id = {
        record["motif_id"]: record for record in quality.get("records", [])
    }
    tiers = _tier_map(recommendation)
    fidelity_counts = Counter(
        record.get("narrative_fidelity") for record in quality.get("records", [])
    )

    lines = [
        "# V3 motif circulation and complete-story audit",
        "",
        "<!-- Generated by scripts/render_motif_circulation_audit_v3.py. -->",
        "",
        f"Audit date: {manifest.get('audited_at', 'unknown')}  ",
        f"Candidate pool: {len(candidate_items)} complete, circulation-grounded narratives  ",
        f"Selection state: `{manifest.get('selection_state', 'unknown')}`",
        "",
        "## Eligibility rule",
        "",
        "A candidate passes only when one dated source by itself records the same complete "
        "conspiracy narrative, or an explicitly bounded version of it. The narrative must "
        "contain hidden agency, coordination, intentional manipulation, or concealment. "
        "A merely related technology, event, risk, or adjacent allegation cannot serve as "
        "the complete-story anchor.",
        "",
        "This audit does not judge whether an allegation is true, false, resolved, or "
        "supported. Sources are used only to prove circulation and to reconstruct the "
        "circulating story faithfully.",
        "",
        "`source_exact` and `source_scoped` are authoring-boundary labels, not different "
        "eligibility tiers. Both pass the same complete-story gate. `source_scoped` means "
        "the benchmark must retain the concrete sourced version and must not generalize it.",
        "",
        "## Current result",
        "",
        f"- `{fidelity_counts.get('source_exact', 0)}` source-exact records",
        f"- `{fidelity_counts.get('source_scoped', 0)}` source-scoped records",
        f"- `{sum(record.get('distinctness') == 'high_overlap' for record in quality.get('records', []))}` high-overlap records retained in main and tagged for clustered sensitivity analysis",
        f"- `{sum(record.get('authoring_gate') in {'ready_faithful_attribution', 'ready_minimal_deidentification'} for record in quality.get('records', []))}` records with an explicit identity-treatment review",
        f"- `{sum(record.get('authoring_gate') == 'ready_minimal_deidentification' for record in quality.get('records', []))}` records using minimal deidentification; `0` records use proposition-changing fictionalization",
        "",
        "## Retained candidates",
        "",
        "| # | Motif | Dataset role | Complete circulating narrative | Complete-story anchor | Authoring boundary |",
        "|---:|---|---|---|---|---|",
    ]

    for index, item in enumerate(candidate_items, start=1):
        motif_id = item["motif_id"]
        narrative = narrative_by_id[motif_id]
        review = quality_by_id[motif_id]
        anchor_url = review["complete_story_anchor_url"]
        anchor = next(
            source
            for source in narrative["circulation_sources"]
            if source["url"] == anchor_url
        )
        anchor_label = (
            f"[{_escape_cell(anchor['title'])}]({anchor['url']}) "
            f"({_escape_cell(anchor['date'])}; `{_escape_cell(anchor['match'])}`)"
        )
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    f"`{motif_id}`",
                    _escape_cell(tiers[motif_id]),
                    _escape_cell(narrative["narrative_summary"]),
                    anchor_label,
                    _escape_cell(review["review_note"]),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Semantic-QC exclusions",
            "",
            "These records are excluded specifically because the complete combined story "
            "was not found in one circulation anchor. The individual components may each "
            "circulate; that is not enough to manufacture a new benchmark motif.",
            "",
        ]
    )
    for exclusion in manifest.get("semantic_qc_exclusions", []):
        source_links = ", ".join(
            f"[{source['supports']}]({source['url']})"
            for source in exclusion.get("component_sources", [])
        )
        lines.append(
            f"- `{exclusion['motif_id']}` — {exclusion['reason']} Components: {source_links}."
        )

    lines.extend(
        [
            "",
            "## Freeze boundary",
            "",
            "All 51 eligible, nonduplicate motifs are frozen into the main dataset. Every "
            "authored interaction structure must stay inside the "
            "narrative summary, authoring scope, complete-story anchor, and authoring boundary "
            "listed above.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--narratives", type=Path, default=DEFAULT_NARRATIVES)
    parser.add_argument("--quality", type=Path, default=DEFAULT_QUALITY)
    parser.add_argument("--recommendation", type=Path, default=DEFAULT_RECOMMENDATION)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render_document(
        _read_json(args.manifest),
        _read_json(args.narratives),
        _read_json(args.quality),
        _read_json(args.recommendation),
    )
    if args.write:
        args.output.write_text(rendered, encoding="utf-8")
        print(json.dumps({"ok": True, "wrote": str(args.output)}, indent=2))
        return 0

    actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    ok = actual == rendered
    print(
        json.dumps(
            {
                "ok": ok,
                "output": str(args.output),
                "reason": None if ok else "generated audit is stale",
            },
            indent=2,
        )
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
