#!/usr/bin/env python3
"""Render v3 motif-pool coverage and experiment-size projections."""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "configs" / "primary_motif_manifest_v3.json"
DEFAULT_QUALITY = ROOT / "configs" / "motif_quality_review_v3.json"
DEFAULT_RECOMMENDATION = ROOT / "configs" / "motif_selection_recommendation_v3.json"
DEFAULT_CONTEXTS = ROOT / "configs" / "context_variants.json"
DEFAULT_OUTPUT = ROOT / "results" / "audits" / "motif_pool_coverage_v3.md"


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render_document(
    manifest: dict,
    quality: dict,
    recommendation: dict,
    contexts: dict,
) -> str:
    candidates = [
        *manifest.get("motifs", []),
        *manifest.get("additional_eligible_candidates", []),
    ]
    candidate_by_id = {item["motif_id"]: item for item in candidates}
    quality_by_id = {item["motif_id"]: item for item in quality.get("records", [])}
    primary_ids = recommendation["recommended_primary_ids"]
    primary = [candidate_by_id[motif_id] for motif_id in primary_ids]

    pool_categories: dict[str, list[str]] = defaultdict(list)
    primary_categories: dict[str, list[str]] = defaultdict(list)
    for item in candidates:
        pool_categories[item["category"]].append(item["motif_id"])
    for item in primary:
        primary_categories[item["category"]].append(item["motif_id"])

    pool_sensitivity = Counter(
        quality_by_id[item["motif_id"]]["sensitivity"] for item in candidates
    )
    primary_sensitivity = Counter(
        quality_by_id[item["motif_id"]]["sensitivity"] for item in primary
    )
    main_frame_count = len(contexts["sets"]["main_v3"])
    robustness_frame_count = len(contexts["sets"]["reviewer_robustness_v3"])
    structures_per_motif = 3

    def projection(motif_count: int) -> tuple[int, int, int]:
        scenario_units = motif_count * structures_per_motif
        return (
            scenario_units,
            scenario_units * main_frame_count,
            scenario_units * robustness_frame_count,
        )

    primary_projection = projection(len(primary))
    pool_projection = projection(len(candidates))
    primary_identity_review = sum(
        quality_by_id[motif_id]["authoring_gate"]
        in {"ready_faithful_attribution", "ready_minimal_deidentification"}
        for motif_id in primary_ids
    )
    primary_minimal_deidentification = sum(
        quality_by_id[motif_id]["authoring_gate"] == "ready_minimal_deidentification"
        for motif_id in primary_ids
    )
    primary_high_overlap = sum(
        quality_by_id[motif_id]["distinctness"] == "high_overlap"
        for motif_id in primary_ids
    )
    signatures = [item["reasoning_signature"] for item in candidates]

    lines = [
        "# V3 motif-pool coverage audit",
        "",
        "<!-- Generated by scripts/render_motif_pool_coverage_v3.py. -->",
        "",
        f"Audit date: {manifest.get('audited_at', 'unknown')}  ",
        f"Pool assessment: `{recommendation['candidate_pool_assessment']}`  ",
        f"Selection state: `{manifest['selection_state']}`",
        "",
        "## Summary",
        "",
        f"- {len(candidates)} eligible complete narratives across {len(pool_categories)} substantive categories",
        f"- {len(primary)} frozen main narratives across {len(primary_categories)} categories",
        f"- {len(set(signatures))}/{len(signatures)} unique reasoning signatures",
        f"- {primary_high_overlap} high-overlap records retained and tagged for clustered sensitivity analysis",
        f"- {primary_identity_review} main records received explicit identity-treatment review",
        f"- {primary_minimal_deidentification} main records use minimal deidentification; none use proposition-changing fictionalization",
        "- All 51 eligible, nonduplicate motifs are frozen into the main dataset",
        "",
        "## Size projection",
        "",
        "A scenario unit is one motif in one of the three matched interaction structures. "
        "A condition row is one scenario unit under one framing/paraphrase condition, before "
        "multiplying by target models, seeds, or replicates.",
        "",
        "| Scope | Motifs | Scenario units (×3 structures) | Main-v3 rows (×5 frames) | Full paraphrase rows (×17 variants) |",
        "|---|---:|---:|---:|---:|",
        f"| Frozen main | {len(primary)} | {primary_projection[0]} | {primary_projection[1]} | {primary_projection[2]} |",
        f"| Entire candidate pool | {len(candidates)} | {pool_projection[0]} | {pool_projection[1]} | {pool_projection[2]} |",
        "",
        "The 17-condition robustness set is nested inside the same five frame families: "
        "one neutral condition and four paraphrases for each of the four non-neutral families. "
        "It is not a 17-frame taxonomy.",
        "",
        "## Category coverage",
        "",
        "| Category | Pool | Frozen main | Main motif IDs |",
        "|---|---:|---:|---|",
    ]
    for category in sorted(pool_categories):
        ids = primary_categories.get(category, [])
        lines.append(
            f"| `{_escape(category)}` | {len(pool_categories[category])} | {len(ids)} | "
            + (", ".join(f"`{motif_id}`" for motif_id in ids) if ids else "—")
            + " |"
        )

    lines.extend(
        [
            "",
            "## Sensitivity and authoring burden",
            "",
            "| Sensitivity class | Pool | Proposed primary |",
            "|---|---:|---:|",
        ]
    )
    for sensitivity in sorted(pool_sensitivity):
        lines.append(
            f"| `{_escape(sensitivity)}` | {pool_sensitivity[sensitivity]} | "
            f"{primary_sensitivity[sensitivity]} |"
        )

    largest_primary_categories = sorted(
        primary_categories.items(), key=lambda pair: (-len(pair[1]), pair[0])
    )
    lines.extend(
        [
            "",
            "## Coverage judgment",
            "",
            "The frozen main benchmark includes the entire eligible 51-motif pool across "
            "all 24 categories. Its largest concentrations are "
            + ", ".join(
                f"`{category}` ({len(ids)})"
                for category, ids in largest_primary_categories[:4]
            )
            + ". These concentrations should be treated as an explicit design choice, not "
            "as a reason to use motif-family clustering, not to discard eligible narratives.",
            "",
            "Further expansion is paused by this rule:",
            "",
            f"> {recommendation['expansion_stop_rule']}",
            "",
            "The selection boundary is frozen. The next dataset-content action is to author "
            "exactly three matched interaction structures per motif, staying within each "
            "complete-story anchor and authoring boundary.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--quality", type=Path, default=DEFAULT_QUALITY)
    parser.add_argument("--recommendation", type=Path, default=DEFAULT_RECOMMENDATION)
    parser.add_argument("--contexts", type=Path, default=DEFAULT_CONTEXTS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render_document(
        _read_json(args.manifest),
        _read_json(args.quality),
        _read_json(args.recommendation),
        _read_json(args.contexts),
    )
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        print(json.dumps({"ok": True, "wrote": str(args.output)}, indent=2))
        return 0

    actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    ok = actual == rendered
    print(
        json.dumps(
            {
                "ok": ok,
                "output": str(args.output),
                "reason": None if ok else "generated coverage audit is stale",
            },
            indent=2,
        )
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
